# Hill Cipher


imports

In [2]:
import string 
import numpy as np

Hill encryption algorithm

In [3]:
def hill_encryption ( text , key):
    
    #func: creat secret matrix 
    def matrix (key):
        sqrt = int(np.sqrt(len(key)))
        key = list(key)
        key_matrix = np.array(list(map(int, key))).reshape(sqrt, sqrt)
        return key_matrix
    
    # func: add padding letters if the text not the same length of the matrix key
        # splilt the Text to sub text with the length of the matrix key , creat the vectors of sub Text
    def Text_new(text):
        sqrt = int(np.sqrt(len(key)))
        text = list(text.lower().replace(" " , ""))
        alphabet = list(string.ascii_lowercase)
        
        while (len(text)%sqrt) != 0 :
                text.append("z")
        
        text_new = []
        for i in range(len(text)):
            for j in range(len(alphabet)):
                if text[i] == alphabet[j]:
                    text_new.append(j)           
        
        num = len (text) // sqrt
        text  = np.array(text_new).reshape(num , sqrt , 1)
        
        return text 
    
    
    Matrix = matrix (key) 
    Text = Text_new(text.lower())
    result = ""
    
    print("Matrix" );print( Matrix);print()
    print("The plain text");print(Text)
    #apply hill cipher encryption
    for i in range(len(Text)):
        sub = np.mod(np.dot( Matrix , Text[i]), 26)
        for j in range(len(Matrix)):
            result+= chr(int(sub[j])+97)
    
    
    return result
    

In [6]:
print("the secret key --  from 1 to 9")
      
key= "1234"
Plain_text = "ESLAMAHMED"

text_encrypt = hill_encryption ( Plain_text , key)
print ("Plain Text : " + Plain_text)
print ("Cipher: " + text_encrypt)

the secret key -  from 1 to 10
Matrix
[[1 2]
 [3 4]]

The plain text
[[[ 4]
  [18]]

 [[11]
  [ 0]]

 [[12]
  [ 0]]

 [[ 7]
  [12]]

 [[ 4]
  [ 3]]]
Plain Text : ESLAMAHMED
Cipher: oglhmkfrky
